from __future__ import annotations

import logging
import os
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

log = logging.getLogger(__name__)

_MINIMAL_CONTENT = "# Project Decisions\n\nNo decisions recorded yet.\n"


def generate_rules(
    project_root: str,
    decisions_db_path: str | None = None,
    decisions_sql_path: str | None = None,
    output_path: str | None = None,
) -> str:
    root = Path(project_root)
    db_path = Path(decisions_db_path) if decisions_db_path else root / ".claude" / "decisions.db"
    sql_path = Path(decisions_sql_path) if decisions_sql_path else root / ".claude" / "decisions.sql"
    out_path = Path(output_path) if output_path else root / ".claude" / "rules" / "decisions.md"

    out_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        conn = _open_db(db_path, sql_path)
    except Exception:
        log.warning("Could not open decision store; writing minimal rules file")
        out_path.write_text(_MINIMAL_CONTENT, encoding="utf-8")
        return str(out_path)

    if conn is None:
        out_path.write_text(_MINIMAL_CONTENT, encoding="utf-8")
        return str(out_path)

    try:
        rows = conn.execute(
            "SELECT d.id, d.content, d.reasoning, ds.scope_type, ds.scope_value "
            "FROM decisions d "
            "LEFT JOIN decision_scopes ds ON d.id = ds.decision_id "
            "WHERE d.status = 'active' "
            "ORDER BY d.id"
        ).fetchall()
    except sqlite3.OperationalError:
        log.warning("Failed to query decisions; writing minimal rules file")
        conn.close()
        out_path.write_text(_MINIMAL_CONTENT, encoding="utf-8")
        return str(out_path)

    conn.close()

    if not rows:
        out_path.write_text(_MINIMAL_CONTENT, encoding="utf-8")
        return str(out_path)

    md = _render_markdown(rows, project_root)
    out_path.write_text(md, encoding="utf-8")
    return str(out_path)


def _open_db(db_path: Path, sql_path: Path) -> sqlite3.Connection | None:
    if db_path.exists():
        conn = sqlite3.connect(str(db_path), timeout=2)
        conn.execute("PRAGMA journal_mode=WAL")
        return conn

    if sql_path.exists():
        content = sql_path.read_text(encoding="utf-8").strip()
        if not content:
            return None
        conn = sqlite3.connect(":memory:")
        conn.executescript(content)
        return conn

    return None


def _render_markdown(rows: list[tuple], project_root: str) -> str:
    global_decisions: list[tuple[int, str]] = []
    scoped: dict[str, list[tuple[int, str]]] = defaultdict(list)
    seen_global: set[int] = set()

    for did, content, _reasoning, scope_type, scope_value in rows:
        if scope_type is None and scope_value is None:
            if did not in seen_global:
                global_decisions.append((did, content))
                seen_global.add(did)
        else:
            scoped[scope_value].append((did, content))

    lines = [
        "# Project Decisions",
        "",
        "> Auto-generated by decision_memory. Do not edit manually.",
        f"> Regenerate: python3 -m decision_memory.rules_generator {project_root}",
        "",
    ]

    if global_decisions:
        lines.append("## Global decisions")
        lines.append("")
        for did, content in global_decisions:
            lines.append(f"- [decision-{did}] {content}")
        lines.append("")

    if scoped:
        lines.append("## File-scoped decisions")
        lines.append("")
        for scope_value in sorted(scoped):
            lines.append(f"### `{scope_value}`")
            for did, content in scoped[scope_value]:
                lines.append(f"- [decision-{did}] {content}")
            lines.append("")

    if not global_decisions and not scoped:
        lines.append("No decisions recorded yet.")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: python3 -m decision_memory.rules_generator <project_root>", file=sys.stderr)
        sys.exit(1)
    result = generate_rules(sys.argv[1])
    print(result)
