#!/usr/bin/env bash
set -e

PROJECT_ROOT="$1"
EPIC_SLUG="$2"
EPIC_TITLE="$3"

if [ -z "$PROJECT_ROOT" ] || [ -z "$EPIC_SLUG" ] || [ -z "$EPIC_TITLE" ]; then
  echo "Usage: generate-pr-body.sh <project-root> <epic-slug> <epic-title>" >&2
  exit 1
fi

COMMITS=$(git -C "$PROJECT_ROOT" log "main..epic/${EPIC_SLUG}" --oneline 2>/dev/null || true)

echo "# ${EPIC_TITLE}"
echo ""

if [ -n "$COMMITS" ]; then
  echo "## Stories"
  echo ""
  while IFS= read -r line; do
    echo "- ${line}"
  done <<< "$COMMITS"
else
  echo "## Stories"
  echo ""
  echo "- No commits yet on this epic branch"
fi

echo ""
echo "---"
echo "Generated by Claude Code pipeline"
