#!/bin/bash
# Injects CLAUDE.md into Claude's context at session start.
# Orchestration-specific context (ORCHESTRATION.md, rendered-prefs sidecar, agenda)
# is only loaded when working inside the ~/.claude/ project.

source "$(dirname "$0")/lib/profile.sh"
require_profile 1

export PYTHONPATH="$HOME/.claude"

# Display active hook profile
ACTIVE_PROFILE="standard"
if [[ -f "$HOME/.claude/hook-profile" ]]; then
  ACTIVE_PROFILE=$(cat "$HOME/.claude/hook-profile" 2>/dev/null)
fi
if [[ -n "$CLAUDE_HOOK_PROFILE" && "$ACTIVE_PROFILE" == "standard" ]]; then
  ACTIVE_PROFILE="$CLAUDE_HOOK_PROFILE"
fi
echo "Hook profile: $ACTIVE_PROFILE"
echo ""

# Reconciliation: warn about dead hook references in settings.json
(
  python3 -m hooks.lib.session_reconcile "$HOME/.claude/settings.json"
) 2>/dev/null || true

echo "=== SESSION CONTEXT: MANDATORY PRE-READ ==="
echo "The following files have been loaded into your context. You MUST treat their"
echo "rules as active constraints before responding to any message this session."
echo ""
echo "--- ~/.claude/CLAUDE.md ---"
cat "$HOME/.claude/CLAUDE.md"
echo ""

# Orchestration context — only when working in the ~/.claude/ project
if [[ "$PWD" == "$HOME/.claude" || "$PWD" == "$HOME/.claude/"* ]]; then
  echo "--- ~/.claude/ORCHESTRATION.md ---"
  cat "$HOME/.claude/ORCHESTRATION.md"
  echo ""
  # Migrate correction_groups schema: add text/source columns if missing
  DB_FILE_PREFS="$HOME/.claude/.claude/epics.db"
  if [[ -f "$DB_FILE_PREFS" ]]; then
    python3 -m hooks.lib.session_db_migrate "$DB_FILE_PREFS"
  fi

  # Render behavioral preferences from DB to sidecar file
  RENDERED_PREFS="$HOME/.claude/.claude/rendered-prefs.md"
  if [[ -f "$DB_FILE_PREFS" ]]; then
    python3 -m hooks.lib.session_render_prefs "$DB_FILE_PREFS" "$RENDERED_PREFS"
  else
    # No DB — write empty sidecar
    echo "# Behavioral Preferences" > "$RENDERED_PREFS"
    echo "" >> "$RENDERED_PREFS"
    echo "_No database available._" >> "$RENDERED_PREFS"
  fi

  # Render decision health scores (negative signals) to sidecar
  if [[ -f "$DB_FILE_PREFS" ]]; then
    python3 -m hooks.lib.session_render_health "$DB_FILE_PREFS" "$RENDERED_PREFS"
  fi

  # Stale decisions sidecar (generated by stop_processor.py Stage 6)
  STALE_DECISIONS="$HOME/.claude/.claude/stale-decisions.md"
  if [[ -s "$STALE_DECISIONS" ]]; then
    echo ""
    echo "--- Stale Decisions ---"
    cat "$STALE_DECISIONS"
    echo ""
  fi

  if [[ -f "$HOME/.claude/session-handoff.md" ]]; then
    echo "=== SESSION HANDOFF (from previous session) ==="
    cat "$HOME/.claude/session-handoff.md"
    echo ""
  fi

  # Compact OpenMemory query — top 5 tool learnings
  OM_DB="$HOME/.claude/.claude/openmemory.sqlite"
  if [[ -f "$OM_DB" ]]; then
    python3 -m hooks.lib.session_om_query "$OM_DB"
  fi

  # Trust calibration summary
  RUN_STATE_DB="$HOME/.claude/.claude/run-state.db"
  if [[ -f "$RUN_STATE_DB" ]]; then
    python3 -m hooks.lib.session_trust "$RUN_STATE_DB"
  fi

  # Background: compute decision freshness scores (no session output)
  if [[ -f "$HOME/.claude/.claude/decisions.sql" || -f "$HOME/.claude/.claude/decisions.db" ]]; then
    nohup python3 "$HOME/.claude/scripts/decision-freshness.py" --project-root "$HOME/.claude" > "$CLAUDE_TEMP_DIR/decision-freshness-${CLAUDE_SESSION_ID:-$$}.log" 2>&1 &
  fi

  SESSION_ID=$(echo "$CLAUDE_SESSION_ID" | tr -dc 'a-zA-Z0-9')

  # OpenMemory health check — warn if Ollama is unreachable
  if ! curl -s --connect-timeout 2 http://localhost:11434/api/tags >/dev/null 2>&1; then
    echo ""
    echo "=== OPENMEMORY WARNING ==="
    echo "  Ollama not reachable at localhost:11434."
    echo "  Memory queries disabled this session. Run: ollama serve"
    echo ""
  fi

  # Session-start timestamp for debrief freshness check
  echo "$(date +%s)" > "$CLAUDE_TEMP_DIR/session-start-${SESSION_ID}"

  # Background: decision freshness scoring (no session output)
  if [[ -f "$HOME/.claude/.claude/decisions.sql" || -f "$HOME/.claude/.claude/decisions.db" ]]; then
    nohup python3 "$HOME/.claude/scripts/decision-freshness.py" --project-root "$HOME/.claude" > "$CLAUDE_TEMP_DIR/decision-freshness-${SESSION_ID}.log" 2>&1 &
  fi

  # Session agenda + stale detection
  DB_FILE="$HOME/.claude/.claude/epics.db"

  if [[ -f "$DB_FILE" ]]; then
    python3 -m hooks.lib.session_agenda "$DB_FILE" "$HOME/.claude"

  # Correction patterns — from correction_groups DB table
  if [[ -f "$DB_FILE" ]]; then
    python3 -m hooks.lib.session_agenda --corrections "$DB_FILE"
  fi

  fi
fi

echo "=== END SESSION CONTEXT ==="

exit 0
