-- decision_memory dump v2
-- generated 2026-03-20T17:06:18.286019+00:00

CREATE TABLE IF NOT EXISTS decisions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    reasoning TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'deprecated', 'superseded', 'violated')),
    source TEXT NOT NULL DEFAULT 'human'
        CHECK (source IN ('human', 'ai-discovered', 'ai-proposed')),
    superseded_by INTEGER REFERENCES decisions(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    domain TEXT
);

CREATE TABLE IF NOT EXISTS decision_scopes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    decision_id INTEGER NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('file', 'pattern', 'tech')),
    scope_value TEXT NOT NULL
);

INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (1, 'All OpenMemory writes must go through om_write.py', 'Prevents uncontrolled memory growth', 'deprecated', 'human', NULL, '2026-03-15T20:45:35.482051+00:00', '2026-03-16T23:00:46.005281+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (2, 'Memory infra limited to 3 persistence surfaces', 'Reduce complexity, four surfaces killed', 'deprecated', 'human', NULL, '2026-03-15T20:45:35.485116+00:00', '2026-03-16T22:20:21.997222+00:00', NULL);
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (3, 'Context injection: Tier 1 always, Tier 2 keyword, Tier 3 async', 'Prevents context bloat', 'deprecated', 'human', NULL, '2026-03-15T20:45:35.488002+00:00', '2026-03-16T22:20:23.439605+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (4, 'Embedding logic in hooks/lib/embedding_utils.py only', 'Single source of truth', 'deprecated', 'human', NULL, '2026-03-15T20:45:35.490912+00:00', '2026-03-16T22:20:24.683896+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (5, 'Never commit directly to main or dev', 'All work on named feature branches', 'superseded', 'human', 26, '2026-03-15T20:45:35.493775+00:00', '2026-03-16T21:44:09.786686+00:00', NULL);
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (6, 'Memory infrastructure limited to 3 persistence surfaces: correction_groups (epics.db), rendered-prefs.md (sidecar), openmemory.sqlite. All other surfaces (corrections.md, correction-tallies.jsonl, om-ops.json, tool-learnings.md) are dead/redundant and must not be recreated.', '4 of 7 surfaces were dead, redundant, or machine-only with DB equivalents. corrections.md dual role replaced by log-correction.sh → DB. tool-learnings.md duplicates OpenMemory. Source: decision-79.', 'active', 'human', NULL, '2026-03-15T20:54:24.567378+00:00', '2026-03-15T20:54:24.567378+00:00', 'general,hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (7, 'All OpenMemory writes route through hooks/lib/om_write.py — never direct INSERT. om_write() sets feedback_score=0.5 default, handles tag validation, enforces per-tag budgets, and does embedding-based dedup at 0.85 threshold.', 'Single fix addresses dedup bypass and immediate pruning bugs. MCP server sys.path must include project root for import. Source: decision-104.', 'active', 'human', NULL, '2026-03-15T20:54:30.615199+00:00', '2026-03-15T20:54:30.615199+00:00', 'hooks,mcp');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (8, 'Embedding logic consolidated: MCP server adds project root to sys.path, imports from hooks.lib.embedding_utils — single source of truth. No duplicate embedding code.', 'Same project, same repo. Coupling is real but acceptable — if hooks/lib moves, import breaks obviously (ImportError at startup). Source: decision-105.', 'active', 'human', NULL, '2026-03-15T20:54:31.713226+00:00', '2026-03-15T20:54:31.713226+00:00', 'hooks,mcp');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (9, 'test content', 'Dual detection paths (shell + Python) caused drift, double-counting, and let junk get promoted to behavioral-prefs.md. Source: decision-43.', 'active', 'human', NULL, '2026-03-15T20:54:34.732517+00:00', '2026-03-16T23:03:07.079013+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (10, 'Correction pipeline single authority: unified process_session_corrections() in signal_processor.py. session-learning-check.sh Section 2 reduced to a 5-line call into Python.', 'Dual detection caused logic drift, double-counting, and bugs harder to trace. Single codepath = single place to fix. Source: decision-75.', 'active', 'human', NULL, '2026-03-15T20:54:37.087819+00:00', '2026-03-15T20:54:37.087819+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (11, 'Correction detection uses semantic delta (cosine similarity against curated prototypes via Ollama nomic-embed-text, threshold 0.55) — not regex. Regex can''t distinguish instructions from corrections.', 'Regex matched surface patterns (''use '', ''stop '', ''just '') which couldn''t distinguish instructions from corrections. Semantic embeddings capture intent. Source: decision-74.', 'active', 'human', NULL, '2026-03-15T20:54:44.026177+00:00', '2026-03-15T20:54:44.026177+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (12, 'Behavioral prefs use sidecar file (.claude/rendered-prefs.md, git-ignored) generated from DB by SessionStart hook, loaded via @import in CLAUDE.md. Survives compaction because @imports are re-read from disk.', 'SessionStart stdout is a conversation message that gets compressed. The sidecar is compaction-resilient. DB is source of truth, sidecar is the injection mechanism. Source: decision-73.', 'active', 'human', NULL, '2026-03-15T20:54:48.901697+00:00', '2026-03-15T20:54:48.901697+00:00', 'general,hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (13, 'Context injection is tiered: Tier 1 (SessionStart, always: CLAUDE.md, ORCHESTRATION.md, behavioral-prefs.md, compact agenda). Tier 2 (UserPromptSubmit keyword-triggered: infrastructure docs, full story details). Tier 3 (background/async: distillation, correction patterns).', 'Lost in the Middle research: 13.9-85% accuracy degradation with increasing context. Tiered injection cuts startup tokens ~50%. UserPromptSubmit fires once per message before processing. Source: decision-66.', 'active', 'human', NULL, '2026-03-15T20:54:53.859419+00:00', '2026-03-15T20:54:53.859419+00:00', 'general,hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (14, 'Memory snapshot at session start drops behavioral-pref query from OpenMemory entirely — rendered-prefs.md already covers it. Only tool-learning entries are queried from OpenMemory at startup.', 'behavioral-prefs.md is eagerly loaded every session via CLAUDE.md @import. OpenMemory behavioral-pref entries are a subset — pure redundancy. Tool learnings are NOT in prefs.md so they provide non-redundant value. Source: decision-67.', 'active', 'human', NULL, '2026-03-15T20:54:57.572578+00:00', '2026-03-15T20:54:57.572578+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (15, 'Stop hook uses async background subprocess: fast sync path (<1s mtime check) + slow background path (nohup python3 stop_processor.py). Background process handles signal processing, session summary, distillation. fcntl.flock advisory locking auto-releases on crash.', '10s async timeout kills Ollama-dependent work. Background subprocess with nohup/disown detaches fully. PID lockfile prevents duplicate runs. WAL mode prevents DB lock contention. Source: decisions 80, 103.', 'active', 'human', NULL, '2026-03-15T20:55:01.950449+00:00', '2026-03-15T20:55:01.950449+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (16, 'SESSION_ID uses CLAUDE_SESSION_ID env var only — no PID fallback. Empty CLAUDE_SESSION_ID (subagent context) means no permission, which is correct behavior.', 'PPID differs per hook invocation (each hook is a new subprocess), making PID fallback useless. Subagents shouldn''t grant protected-file permissions. Source: decision-106.', 'deprecated', 'human', NULL, '2026-03-15T20:55:09.854050+00:00', '2026-03-16T22:08:46.377444+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (17, 'Transient execution state lives in separate run-state.db (~/.claude/.claude/run-state.db), not epics.db. Scripts write story outcomes, batch verifications, merge results here. Keeps epics.db contract intact — Claude writes only plan_file and state via pm_update_story.', 'Survives context compaction and session crashes. Scripts own their own state without coordination with Gemini pm_* tools. Source: decision-76.', 'active', 'human', NULL, '2026-03-15T20:55:14.673295+00:00', '2026-03-15T20:55:14.673295+00:00', 'scripts,skills');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (18, 'Worktree creation happens in pre-launch (worktree-setup.sh called by resolution subagent before coder agent). Coder agents only verify they''re on the correct branch — they never create worktrees. Main session MUST NOT use EnterWorktree or git worktree add.', 'Eliminates duplicated bash in coder/test prompts. Worktree creation is 100% deterministic — no LLM judgment needed. Compliant with ORCHESTRATION.md §1 worktree prohibition. Source: decision-77.', 'deprecated', 'human', NULL, '2026-03-15T20:55:19.559178+00:00', '2026-03-16T22:15:25.759876+00:00', 'scripts,skills');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (19, 'Policy-mechanism split: deterministic/testable operations (worktree setup, build verify, merge gate, diff gate, worktree cleanup) go to scripts. Orchestration, agent coordination, conflict reclassification, and failure attribution stay in SKILL.md.', 'If it requires LLM judgment or Agent tool calls → SKILL.md. If deterministic and testable → script. Shared scripts eliminate ~100 lines of cross-skill duplication. Source: decision-78.', 'active', 'human', NULL, '2026-03-15T20:55:23.656100+00:00', '2026-03-15T20:55:23.656100+00:00', 'scripts,skills');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (20, 'Hook generator must abort (return None) when the only possible condition would be ''if true''. No hook is better than a noisy hook — alarm fatigue from false warnings trains users to ignore all compliance warnings.', 'Alarm fatigue defeats the purpose of the compliance system. Source: decision-44.', 'deprecated', 'human', NULL, '2026-03-15T20:55:26.475511+00:00', '2026-03-16T22:08:46.377444+00:00', 'hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (21, 'Per-project decision memory uses hybrid SQL dump: .claude/decisions.sql committed to git (text-based, diffable), local .claude/decisions.db rebuilt on demand with sqlite-vec index. DB is a computed artifact — gitignored, rebuilt from dump via hash check.', 'SQL dump preserves relational structure while being git-diffable. Avoids binary merge conflicts. Source: decision-117.', 'active', 'human', NULL, '2026-03-15T20:55:35.457170+00:00', '2026-03-15T20:55:35.457170+00:00', 'decision-memory,general');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (22, 'Per-project decision memory uses FastEmbed ONNX + nomic-embed-text-v1.5 at 256d Matryoshka — SEPARATE from existing Ollama 768d system. No migration, no backward compat concerns between the two embedding systems.', 'Portability is primary goal. FastEmbed requires only pip install, no daemon. 256d Matryoshka gives 98.8% quality at 3x storage reduction. Source: decision-118.', 'active', 'human', NULL, '2026-03-15T20:55:39.228470+00:00', '2026-03-15T20:55:39.228470+00:00', 'decision-memory');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (23, 'Decision injection uses three layers: (1) MCP hook-triggered auto (primary — fires when MCP server running), (2) generated glob rules (fallback — works on new machines without MCP), (3) explicit MCP query (escape hatch — semantic search beyond file-scoped matches).', 'No AI coding tool does edit-time auto-injection today. Three layers cover all scenarios. Source: decision-119.', 'active', 'human', NULL, '2026-03-15T20:55:43.038673+00:00', '2026-03-15T20:55:43.038673+00:00', 'decision-memory,mcp');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (24, 'Per-project .decisions.db lives in the TARGET project''s .claude/ directory, NOT ~/.claude/ — does not count against decision-79''s 3 persistence surface limit. It''s per-project portable state (like .git/), not user infrastructure.', 'decision-79 limits ~/.claude/ infrastructure to 3 surfaces. Per-project DB is a different category. Source: decision-120.', 'active', 'human', NULL, '2026-03-15T20:55:46.587432+00:00', '2026-03-15T20:55:46.587432+00:00', 'decision-memory,general');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (25, 'friction.json is NOT dead storage — actively written by stop-hook.sh/subagent-stop-hook.sh via parse_friction.py and read by generate-charts.py and cost-summary.py. Do not delete it or remove its references.', 'Plan-writer research incorrectly marked it dead. Corrections track user redirects; friction tracks tool errors, permission denials, retries — different data. Source: decision-40.', 'active', 'human', NULL, '2026-03-15T20:55:50.238326+00:00', '2026-03-15T20:55:50.238326+00:00', 'general,hooks');
INSERT OR REPLACE INTO decisions (id, content, reasoning, status, source, superseded_by, created_at, updated_at, domain) VALUES (26, 'Never commit directly to main. All work merges to dev first, then dev merges to main.', NULL, 'active', 'human', NULL, '2026-03-16T21:44:09.786686+00:00', '2026-03-16T21:44:09.786686+00:00', NULL);

INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (1, 1, 'file', 'hooks/lib/om_write.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (2, 2, 'tech', 'persistence');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (3, 3, 'file', 'hooks/load-session-context.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (4, 3, 'file', 'hooks/inject-tier2-context.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (5, 4, 'file', 'hooks/lib/embedding_utils.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (6, 5, 'tech', 'git-workflow');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (7, 6, 'file', 'CLAUDE.md');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (8, 6, 'file', 'hooks/lib/om_write.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (9, 6, 'file', 'hooks/lib/signal_processor.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (10, 6, 'file', 'hooks/session-learning-check.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (11, 7, 'file', 'hooks/lib/om_write.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (12, 7, 'file', 'mcp-servers/gemini/tools_knowledge.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (13, 8, 'file', 'hooks/lib/embedding_utils.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (14, 8, 'file', 'mcp-servers/gemini/tools_knowledge.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (15, 9, 'file', 'hooks/lib/signal_processor.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (16, 9, 'file', 'hooks/session-learning-check.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (17, 10, 'file', 'hooks/lib/signal_processor.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (18, 10, 'file', 'hooks/session-learning-check.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (19, 11, 'file', 'hooks/lib/signal_processor.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (20, 12, 'file', '.claude/rendered-prefs.md');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (21, 12, 'file', 'CLAUDE.md');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (22, 12, 'file', 'hooks/load-session-context.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (23, 13, 'file', 'hooks/inject-tier2-context.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (24, 13, 'file', 'hooks/load-session-context.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (25, 13, 'file', 'settings.json');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (26, 14, 'file', 'hooks/load-session-context.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (27, 15, 'file', 'hooks/lib/stop_processor.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (28, 15, 'file', 'hooks/session-learning-check.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (29, 16, 'file', 'hooks/guard-protected-files.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (30, 16, 'file', 'hooks/lib/profile.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (31, 17, 'file', 'scripts/*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (32, 17, 'file', 'skills/run-stories/SKILL.md');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (33, 18, 'file', 'scripts/worktree-setup.sh');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (34, 18, 'file', 'skills/run-stories/SKILL.md');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (35, 19, 'file', 'scripts/*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (36, 19, 'file', 'skills/merge-worktree/SKILL.md');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (37, 19, 'file', 'skills/run-stories/SKILL.md');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (38, 20, 'file', 'hooks/lib/hook_generator.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (39, 21, 'file', '.claude/decisions.*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (40, 21, 'file', 'decision_memory/*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (41, 22, 'file', 'decision_memory/*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (42, 23, 'file', 'decision_memory/*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (43, 23, 'file', 'mcp-servers/decisions/*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (44, 24, 'file', '.claude/decisions.*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (45, 24, 'file', 'decision_memory/*');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (46, 25, 'file', 'hooks/lib/parse_friction.py');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (47, 25, 'file', 'tracking/friction.json');
INSERT OR REPLACE INTO decision_scopes (id, decision_id, scope_type, scope_value) VALUES (48, 26, 'tech', 'git-workflow');
